<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="base" params="body_length body_width body_height">

        <link name="base_link">
            <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="silver">
                <color rgba="0.75 0.75 0.75 1"/>
            </material>
            </visual>
            <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            </collision>
            <inertial>
            <mass value="1.0"/>
            <inertia ixx="0.015" iyy="0.0375" izz="0.0375" ixy="0" ixz="0" iyz="0"/>
            </inertial>
        </link>

        <link name="lidar_link">
            <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
            </visual>
            <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            </collision>
            <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
            </inertial>
        </link>

        <joint name="lidar_joint" type="fixed">
            <axis xyz="0 1 0" />
            <origin xyz="0 0 ${(body_height/2) + 0.05}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="lidar_link"/>
        </joint>

        <gazebo reference="lidar_link">
            <sensor name="lidar_link" type="gpu_lidar">
            <gz_frame_id>lidar_link</gz_frame_id>
            <pose>0 0 0 0 0 0</pose>
            <update_rate>10</update_rate>
            <topic>scan</topic>
            <ray>
                <scan>
                <horizontal>
                    <samples>720</samples>
                    <resolution>1</resolution>
                    <min_angle>-3.1415925</min_angle>
                    <max_angle>3.1415925</max_angle>
                </horizontal>
                <vertical>
                    <samples>1</samples>
                    <resolution>0.01</resolution>
                    <min_angle>0</min_angle>
                    <max_angle>0</max_angle>
                </vertical>
                </scan>
                <range>
                <min>0.10</min>
                <max>30.0</max>
                <resolution>0.01</resolution>
                </range>
                <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.01</stddev>
                </noise>
            </ray>
            <always_on>1</always_on>
            <visualize>true</visualize>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>